version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd my-app
      - echo Installing source NPM dependencies...
      #- npm install dotenv
      #- npm install web3
      - rm -rf node_modules
      - rm package-lock.json
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      #- npx create-react-app my-app    
      - cd  my-app
      - npm run start
      #- npm run build

artifacts:
  files:
    - '**/*'
    #- "my-app/build/**/*"
  base-directory: 'my-app/build'
  #discard-paths: yes
